"""Curated narrative for the unchanged fictional intake only. No client reference content."""
def sec(name,text,*ids): return {'name':name,'text':text,'fact_ids':list(ids)}
SAMPLE_DRAFTS={
'Case Study':[
sec('Title','How a logistics cooperative brought delivery exception review into one shared workflow','F1','F3','F4'),
sec('Subtext','Lumen Orchard replaced manual reconciliation with a shared review queue, giving dispatchers delivery records, ownership and review status in one place while retaining their responsibility for final decisions.','F1','F2','F4','F10'),
sec('Context','Lumen Orchard is a fictional regional logistics cooperative whose dispatch team coordinates daily deliveries and reviews exceptions raised by depot teams. The project focused on how those exceptions were reviewed and followed up, rather than changing delivery routing. Its scope was to bring the review process together while keeping decisions about resolution with dispatchers.','F1','F13','F10'),
sec('Key Metrics','• Review time fell by 24% over six months compared with the prior six-month period.','F5'),
sec('The Challenge','Dispatchers previously compared emailed depot updates with a shared spreadsheet to identify unresolved delivery exceptions. This required them to reconcile records before deciding which items needed follow-up.\n\nDifferent versions of the spreadsheet made ownership difficult to establish. Dispatchers contacted depots for clarification before they could prioritise the outstanding work, so identifying an exception and deciding who would act on it remained separate tasks.\n\nManagers then assembled their own summary of unresolved exceptions before planning the next delivery cycle. The team wanted a consistent view of outstanding work without repeating that reconciliation in another summary.','F2','F7','F8'),
sec('The Solution','The team introduced a shared delivery review workflow that brought depot updates and delivery records into one queue. Instead of starting with separate emails and spreadsheet versions, dispatchers could review an exception alongside its source record, assigned owner and current status.\n\nDepot coordinators submit each exception with a delivery reference, a reason and a supporting record. The workflow groups related updates and displays the supporting evidence beside the exception, providing the material dispatchers need for review.\n\nDispatchers check that record, assign an owner and record the next action. Unclear or conflicting updates remain open for clarification, and dispatchers retain the final decision about closure. The queue therefore organises the work while preserving the team’s responsibility for deciding whether an exception has been resolved.\n\nManagers use the same queue to see open exceptions, ownership and review status before planning follow-up. For this task, the shared view replaced the separate spreadsheet summary.','F3','F4','F9','F10','F11'),
sec('The Outcome','Review time fell by 24% over six months compared with the prior six-month period. This result concerns the time spent reviewing exceptions; it does not represent an improvement in delivery speed or a reduction in transport costs.\n\nThe operational change was a common queue for review and follow-up across depots. Source records, ownership and status were visible together, while dispatchers continued to review the evidence and decide whether to close each exception.','F5','F12','F4','F10'),
sec('CTA','[Approved CTA pending]')],
'One-Pager':[
sec('Headline','A shared delivery exception workflow with dispatcher control','F3','F10'),
sec('Client and Context','Lumen Orchard is a fictional regional logistics cooperative. Its dispatch team coordinates daily deliveries and reviews depot exceptions. The project focused on exception review and follow-up; it did not change delivery routing or automate resolution decisions.','F1','F13'),
sec('Challenge','Dispatchers compared emailed depot updates with a shared spreadsheet to find unresolved exceptions. Different versions made ownership difficult to identify, requiring clarification before follow-up could be prioritised. Managers also assembled a separate summary before planning the next delivery cycle.','F2','F7','F8'),
sec('Solution','A shared queue brought delivery records and depot updates together. Coordinators submit the delivery reference, reason and supporting record; the workflow groups related updates and displays the evidence alongside each exception.\n\nDispatchers check the record, assign an owner and record the next action. Conflicting updates remain open for clarification, with dispatchers making the final closure decision. Managers use the same queue for planning follow-up, replacing their separate spreadsheet summary.','F3','F9','F10','F11'),
sec('Impact or Key Results','• Review time fell by 24% over six months compared with the prior six-month period.\n• Source records, ownership and review status are visible in one queue.','F5','F4'),
sec('Why It Matters','The team uses a common view to organise exception review and follow-up across depots while retaining dispatcher judgement. The measured result relates to review time, rather than delivery speed or transport cost.','F12','F10','F4'),
sec('CTA','[Approved CTA pending]')]
}
