let p=null,model=false,step=0,view='facts',busy=false,draftView='read';
const sessionKey='story-studio-session-v4';
function keepSession(){try{if(p)sessionStorage.setItem(sessionKey,JSON.stringify(p));else sessionStorage.removeItem(sessionKey)}catch(e){$('#message').innerHTML='<div class="notice">Browser session storage is full. Keep this tab open and download your draft before leaving.</div>'}}
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(xs,current)=>xs.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('');
const button=(text,action,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
function permitted(){return p.facts.filter(f=>f.status==='confirmed'&&!f.restriction)}
function invalidate(){p.plan_approved=false;Object.values(p.drafts).forEach(d=>{d.validation=null;d.review='Pending human review'})}
async function call(action,extra={}){if(busy)return;busy=true;$('#message').innerHTML='<div class="notice">'+(action==='generate'?'Writing your draft…':['upload','retryExtraction'].includes(action)?'Reading intake sections and completed answers…':action==='validate'?'Checking facts and writing…':action==='regenerate'?'Rewriting this section…':'Saving…')+'</div>';document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:['upload','demo'].includes(action)?null:p,...extra})});let x;try{x=await r.json()}catch(e){throw Error(r.status===413?'This upload exceeds the hosted demo limit. Choose a file under 2.8 MB.':'The server could not finish. Your browser session is retained; retry.')}if(!r.ok)throw Error(x.error);p=x.project;keepSession();if(['upload','demo','retryExtraction'].includes(action)){step=1;view='facts'}if(action==='verify'){step=1;view='plan'}if(action==='plan')step=2;render();$('#message').innerHTML='<p class="save-info">Updated for this browser session</p>'}catch(e){$('#message').innerHTML='<div class="error">'+esc(e.message)+'</div>'}finally{busy=false;render()}}
function renderDisabled(){document.querySelectorAll('button[data-action]').forEach(b=>b.disabled=busy);document.querySelectorAll('[data-confirm]').forEach(b=>{const f=p.facts[+b.dataset.confirm];b.disabled=!!f.restriction||f.status==='restricted'})}
function intro(title,sub){return `<div class="intro"><span class="eyebrow">Step ${step+1} of 3</span><h1>${title}</h1><p class="muted">${sub}</p></div>`}
function factCard(f,i){return `<article class="card fact"><div class="row between"><strong>${esc(f.category)} · ${esc(f.fact_id)}</strong><span class="pill ${f.status}">${esc(f.status)}</span></div><p>${esc(f.wording||'Add evidence below')}</p><div class="row between"><button class="link" data-source="${esc(f.fact_id)}">View source passage ↗</button><button class="${f.status==='confirmed'?'secondary':''}" data-confirm="${i}">${f.status==='confirmed'?'✓ Confirmed':f.status==='restricted'?'Excluded':'Confirm fact'}</button></div><details><summary>Edit fact or restrictions</summary><label>Exact fact wording</label><textarea data-fact="${i}" data-field="wording">${esc(f.wording)}</textarea><div class="fields"><div><label>Category</label><select data-fact="${i}" data-field="category">${opts(['context','challenge','solution','outcome','metric','restricted'],f.category)}</select></div><div><label>Status</label><select data-fact="${i}" data-field="status">${opts(['uncertain','confirmed','missing','restricted'],f.status)}</select></div><div><label>Restricted text to exclude</label><input data-fact="${i}" data-field="restriction" value="${esc(f.restriction)}"></div></div>${f.category==='metric'?'<div class="fields">'+['value','unit','period','qualifier','comparison'].map(k=>`<div><label>${k}</label><input data-fact="${i}" data-field="${k}" value="${esc(f[k])}"></div>`).join('')+'</div>':''}</details></article>`}

function storyRoles(f){const roles=new Set([f.category,...(Array.isArray(f.story_roles)?f.story_roles:[]),...((f.metric_role==='result'||(f.category==='metric'&&(!f.metric_role||f.metric_role==='unknown')&&/\b(fell|rose|reduced|decreased|increased|saved|improved|achieved)\b/i.test(f.wording)&&!/\b(target|expected|projected|planned|potential|forecast)\b/i.test(f.wording)))?['outcome']:[])]);if(f.metric_role==='baseline')roles.delete('outcome');return roles}
function reviewInfo(){
 const exceptions=[],quick=[];
 p.facts.forEach(f=>{if(f.status==='restricted'||f.restriction)return;let reasons=[];if(f.status==='missing')reasons.push('Missing information');if(!f.passage)reasons.push('Missing source passage');if(f.category==='metric'&&!['value','unit','period'].every(k=>f[k]))reasons.push('Metric needs value, unit and period');if(f.needs_review)reasons.push(f.review_reason||'Ambiguity needs review');if(p.manual_review_required&&f.status!=='confirmed'&&!(f.source_excerpt&&f.wording===f.passage&&p.raw.includes(f.passage)))reasons.push('Manual source check needed');if(reasons.length&&f.status!=='confirmed')exceptions.push({fact_id:f.fact_id,reasons});else if(f.status==='uncertain')quick.push(f.fact_id)});
 return {exceptions,quick_confirm_ids:quick,missing_categories:['challenge','solution','outcome'].filter(c=>!p.facts.some(f=>storyRoles(f).has(c)&&!f.restriction&&!['missing','restricted'].includes(f.status)))};
}
function reviewPanel(){
 const info=reviewInfo(),restricted=p.facts.filter(f=>f.status==='restricted'||f.restriction);
 let html=`<div class="card"><div class="row between"><h2>Your intake, at a glance</h2><span class="pill">${info.exceptions.length} optional checks</span></div><p class="muted">${esc(p.file||'Fictional example')} · Here is what we understood from your intake. Reviewing individual facts is optional; you can continue now.</p><div class="summary-grid">`;
 for(const [category,title] of [['context','Client context'],['challenge','The problem'],['solution','What changed'],['outcome','The result']]){let facts=p.facts.filter(f=>storyRoles(f).has(category)&&!f.restriction&&!['restricted','missing'].includes(f.status));html+=`<div><h3>${title}</h3>${facts.length?`<p>${esc(facts[0].wording.length>340?facts[0].wording.slice(0,340)+"…":facts[0].wording)}</p><button class="link" data-source="${esc(facts[0].fact_id)}">Check source ↗</button>`:'<p class="muted">Not yet identified in the extracted facts. You can still continue.</p>'}</div>`}
 html+=`</div><details><summary>Results & metrics (${p.facts.filter(f=>f.category==='metric'&&!f.restriction).length})</summary>${p.facts.filter(f=>f.category==='metric'&&!f.restriction).map(f=>`<p class="muted">${esc(f.wording)} <button class="link" data-source="${esc(f.fact_id)}">Source ↗</button></p>`).join('')||'<p class="muted">No measurable result found. A coherent workflow story may still proceed.</p>'}</details><p class="muted">${restricted.length} restricted facts will be excluded.</p></div>`;
 if(p.extraction_note)html+=`<div class="notice">${esc(p.extraction_note)} ${p.document?button('Retry extraction','retryExtraction','secondary'):''}</div>`;
 if(p.intake)html+=`<details class="card"><summary>Read extracted answers by intake section</summary>${Object.entries(p.intake).map(([group,answers])=>`<h3>${esc(group.replaceAll('_',' '))}</h3>${answers.map(a=>`<p><strong>${esc(a.field)}</strong> ${esc(a.answer)} <button class="link" data-source="${esc(a.fact_id)}">Source ↗</button></p>`).join('')||'<p class="muted">Not identified by extraction.</p>'}`).join('')}</details>`;
 if(info.missing_categories.length)html+=`<div class="notice">Not yet identified in the extracted facts: ${esc(info.missing_categories.join(', '))}. This may be a classification issue, not missing information in your document. Continue with available evidence, or review the source below.</div>`;
 if(info.exceptions.length)html+=`<details class="card"><summary>Optional: review ${info.exceptions.length} flagged facts</summary><p class="muted">You do not have to resolve these to continue. Unclear metrics and unverified claims stay out of the draft until confirmed.</p>`+info.exceptions.map(e=>{const i=p.facts.findIndex(f=>f.fact_id===e.fact_id);return `<p class="muted">${esc(e.reasons.join(' · '))}</p>`+factCard(p.facts[i],i)}).join('')+'</details>';
 html+=`<details class="card"><summary>View all ${p.facts.length} facts & restrictions</summary><p class="muted">Inspect or correct any fact if you wish. Continue confirms the clear, source-backed facts; flagged items and restrictions remain excluded.</p>${p.facts.map(factCard).join('')}${button('+ Add fact','addFact','ghost')}</details><details class="card"><summary>Read complete intake</summary><pre>${esc(p.raw)}</pre></details><div class="card"><h2>Ready to write?</h2><p class="muted">Continue uses the clear, source-backed facts above. Flagged facts stay excluded until you confirm them; restricted facts are never used. Missing story details can remain pending in the draft.</p><details><summary>Writer name (optional)</summary><input id="writer" aria-label="Writer name" value="Writer"></details><div class="actions">${button('Continue with intake →','verify')}<span class="muted">You can return and review facts later.</span></div></div>`;return html;
}

function render(){
 $('#mode').textContent=model?'AI configured': 'AI not connected';
 $('#steps').innerHTML=['Upload','Intake & focus','Draft & review'].map((s,i)=>`<button data-step="${i}" class="${step===i?'active':''}" ${i===1&&!p||i===2&&!p?.plan_approved?'disabled':''}>${i+1} &nbsp; ${s}</button>`).join('');
 let html='';
 if(step===0){html=intro('Your next story starts here.','One intake. One verified story. A draft you can trust and shape.');html+=`<div class="card upload"><div class="upload-symbol">↑</div><h2>Upload your success-story intake</h2><p class="muted">Choose one PDF or Word document to get started.</p><div class="row"><input class="file-input" id="file" type="file" accept=".pdf,.docx" aria-label="Intake file">${button('Read intake →','upload')}</div><p class="muted">${model?'Structured answers are read locally. AI writes and checks the draft.':'No AI key detected. You can still explore the full flow with fictional data.'}</p>${button('Try a fictional example','demo','secondary')}</div>${p?button('Continue current story →','resume','ghost'):''}`}
 else{
 if(p.demo)html+=`<div class="notice">Fictional example · ${model?'Your configured model is available for writing and checks.':'Curated sample; AI checks are unavailable.'} Sample drafts cannot be approved as real client material.</div>`;
 if(step===1){html=intro('What we understood.','Review if you want, or continue with your intake. You can correct details later.')+html;html+=`<div class="tabs"><button data-view="facts" class="${view==='facts'?'active':''}">1. Intake summary</button><button data-view="plan" class="${view==='plan'?'active':''}" ${!p.plan?'disabled':''}>2. Story focus</button></div>`;
 if(view==='facts'){html+=reviewPanel()}
 else{let plan=p.plan;html+=`<div class="card"><h2>Your story focus</h2><p class="muted">This is a short summary of the problem, change and result—not a new template. The same focus guides both formats. Change the emphasis or evidence before approving.</p>${plan.evidence_gaps?.length?`<div class="notice">We have not identified usable ${esc(plan.evidence_gaps.join(', '))} evidence yet. You can continue; unsupported details will stay pending.</div>`:''}<label>The story in a few sentences</label><textarea data-plan="story">${esc(plan.story)}</textarea><label>Lead result</label><select data-plan="lead_metric"><option value="">No lead metric</option>${permitted().filter(f=>f.category==='metric').map(f=>`<option value="${f.fact_id}" ${plan.lead_metric===f.fact_id?'selected':''}>${esc(f.wording)}</option>`).join('')}</select><p class="muted">Using ${plan.selected.length} permitted evidence statements. You can inspect and correct them in Intake summary; no individual selection is required.</p><details><summary>Supporting metrics & limitations</summary><label>Supporting metric IDs, separated by commas</label><input data-plan="supporting_metrics" value="${esc(plan.supporting_metrics.join(', '))}"><label>Limitations</label><textarea data-plan="limitations">${esc(plan.limitations)}</textarea><p class="muted">Excluded facts: ${esc(plan.excluded.join(', '))}</p></details><div class="actions">${button('Approve focus & continue →','plan')}</div></div>`}
 }else{let d=p.drafts[p.format];html=intro('Shape your story.','Edit the draft, check its claims, and keep human approval separate.')+html;html+=`<div class="card row between"><div><h2>Choose your format</h2><span class="pill">Extracted editorial guide applied</span><span class="muted">${p.format==='One-Pager'?'Provisional One-Pager template':'Full Case Study narrative'}</span></div><div class="row"><select id="format" aria-label="Output format" style="width:auto">${opts(['Case Study','One-Pager'],p.format)}</select>${button(d?'Regenerate draft':'Create first draft →','generate')}</div></div>`;
 if(d){const v=d.validation;if(d.generation_note)html+=`<div class="notice">${esc(d.generation_note)}</div>`;html+=`<div class="row between draft-toolbar"><div class="tabs"><button data-draft-view="read" class="${draftView==='read'?'active':''}">Read story</button><button data-draft-view="edit" class="${draftView==='edit'?'active':''}">Edit sections</button></div><span class="muted">${esc(d.engine||'Earlier draft — regenerate to apply new writing guidance')}</span></div>`;html+=`<div class="draft-grid"><div>${draftView==='read'?readerDraft(d):d.sections.map((s,i)=>`<article class="card section"><h3>${esc(s.name)}</h3><textarea data-section="${i}" aria-label="${esc(s.name)}">${esc(s.text)}</textarea><div class="row between"><span class="muted">${s.fact_ids.map(id=>`<button class="link" data-source="${esc(id)}">${esc(id)} ↗</button>`).join(' · ')||'No factual claim'}</span><button data-regenerate="${i}">↻ Rewrite section</button></div></article>`).join('')}</div><aside><div class="card"><h3>Draft checks</h3><span class="pill">${esc(v?.status||'Needs revalidation')}</span><p class="muted">Edits require fresh checks. Automated results never mean human approval.</p>${button('Check this draft','validate')}${v?`<details><summary>Check availability</summary>${v.checks.map(c=>`<div class="check">${esc(c.name)}<span>${esc(c.state)}</span></div>`).join('')}<p class="muted">${esc(v.reference_note)}</p></details>${v.findings.map(f=>`<div class="finding ${f.level}"><strong>${esc(f.level==='block'?'Blocking issue':'Warning')} · ${esc(f.section)}</strong><p>${esc(f.reason)}</p><details><summary>Evidence & correction</summary><pre>${esc(f.text)}</pre><p>${esc(f.source)} ${esc(f.correction)}</p></details></div>`).join('')}`:''}</div><div class="card"><h3>Human review</h3><p class="muted">${esc(d.review)}</p><label>Reviewer</label><input id="reviewer" value="Local reviewer">${button('Approve reviewed draft','review')}${button('Request changes','changes','secondary')}<details><summary>Save & share draft</summary>${button('Keep current version in session','save','secondary')}${button('Copy draft','copy','secondary')}${button('Download text','download','secondary')}<p class="muted">${p.history.length} earlier revisions in this session.</p></details></div></aside></div>`}
 html+=references();}
 }
 $('#app').innerHTML=html;bind();renderDisabled();document.querySelectorAll('[data-section]').forEach(el=>{el.style.height='auto';el.style.height=Math.max(100,el.scrollHeight+4)+'px'});
}
function prose(text){return text.split(/\n\s*\n/).map(part=>/^[•*-]\s/.test(part.trim())?'<ul>'+part.split('\n').filter(Boolean).map(line=>'<li>'+esc(line.replace(/^[•*-]\s*/,''))+'</li>').join('')+'</ul>':'<p>'+esc(part).replace(/\n/g,'<br>')+'</p>').join('')}
function readerDraft(d){return '<article class="card story-paper">'+d.sections.map((s,i)=>{let title=i===0,sub=s.name==='Subtext',hidden=['Subtext','Context','Key Metrics','CTA'].includes(s.name);return `<section class="story-part ${sub?'story-subtext':''}">${title?'<h1>'+esc(s.text)+'</h1>':(hidden?'':'<h2>'+esc(s.name)+'</h2>')+prose(s.text)}<div class="story-evidence">${s.fact_ids.map(id=>`<button class="link" data-source="${esc(id)}">${esc(id)} ↗</button>`).join(' · ')} <button class="link" data-edit-part="${i}">Edit${title?' headline':' section'}</button></div></section>`}).join('')+'</article>'}
function references(){return `<details class="card"><summary>Style references · ${p.references.length} examples</summary><p class="muted">Only approved active references for this format are used. No examples? Editorial rules apply.</p>${p.references.map((r,i)=>`<div class="card"><strong>${esc(r.title)}</strong><p class="muted">${esc(r.format)} · version ${esc(r.version)}</p><label><input style="width:auto" type="checkbox" data-ref="${i}" data-field="approved" ${r.approved?'checked':''}> Approved</label><label><input style="width:auto" type="checkbox" data-ref="${i}" data-field="active" ${r.active?'checked':''}> Active</label><details><summary>Read reference</summary><pre>${esc(r.text)}</pre></details><button class="ghost" data-remove-ref="${i}">Remove</button></div>`).join('')}<details><summary>Add example</summary><label>Title</label><input id="rt"><label>Format</label><select id="rf">${opts(['Case Study','One-Pager'],p.format)}</select><div class="fields">${['industry','use_case','outcome','version'].map(k=>`<div><label>${k.replace('_',' ')}</label><input id="r${k}" value="${k==='version'?'1':''}"></div>`).join('')}</div><label>Reference entities, separated by commas</label><input id="re"><label>Example text</label><textarea id="rx"></textarea>${button('Add unapproved example','addRef','secondary')}</details>${button('Save reference settings','references','secondary')}</details>`}
function bind(){document.querySelectorAll('[data-draft-view]').forEach(b=>b.onclick=()=>{draftView=b.dataset.draftView;render()});document.querySelectorAll('[data-edit-part]').forEach(b=>b.onclick=()=>{draftView='edit';render();document.querySelector('[data-section="'+b.dataset.editPart+'"]').focus()});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;render();window.scrollTo(0,0)});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>{p.facts[+b.dataset.confirm].status='confirmed';invalidate();keepSession();render()});document.querySelectorAll('[data-fact]').forEach(el=>el.onchange=()=>{p.facts[+el.dataset.fact][el.dataset.field]=el.value;if(el.dataset.field==='category'){p.facts[+el.dataset.fact].story_roles=[el.value];p.facts[+el.dataset.fact].metric_role='unknown'}invalidate();keepSession();render()});document.querySelectorAll('[data-plan]').forEach(el=>el.onchange=()=>{p.plan[el.dataset.plan]=el.dataset.plan==='supporting_metrics'?el.value.split(',').map(x=>x.trim()).filter(Boolean):el.value;p.plan_approved=false});document.querySelectorAll('[data-selected]').forEach(el=>el.onchange=()=>{p.plan.selected=el.checked?[...new Set([...p.plan.selected,el.dataset.selected])]:p.plan.selected.filter(x=>x!==el.dataset.selected);p.plan_approved=false});document.querySelectorAll('[data-section]').forEach(el=>el.onchange=()=>{let d=p.drafts[p.format];p.history.push(structuredClone(d));d.sections[+el.dataset.section].text=el.value;call('edit')});document.querySelectorAll('[data-regenerate]').forEach(b=>b.onclick=()=>call('regenerate',{index:+b.dataset.regenerate}));document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>showSource(b.dataset.source));document.querySelectorAll('[data-ref]').forEach(el=>el.onchange=()=>{p.references[+el.dataset.ref][el.dataset.field]=el.checked});document.querySelectorAll('[data-remove-ref]').forEach(b=>b.onclick=()=>{p.references.splice(+b.dataset.removeRef,1);call('references')});if($('#format'))$('#format').onchange=e=>{p.format=e.target.value;call('save')}}
async function action(a){if(a==='upload'){let f=$('#file').files[0];if(!f){$('#message').innerHTML='<div class="error">Choose one PDF or DOCX first.</div>';return}if(f.size>2800000){alert('Maximum file size for this demo: 2.8 MB');return}let bytes=new Uint8Array(await f.arrayBuffer()),str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));return call('upload',{name:f.name,data:btoa(str)})}if(a==='resume'){step=p.plan_approved?2:1;return render()}if(a==='verify')return call(a,{writer:$('#writer')?.value||'Writer',confirm_ids:reviewInfo().quick_confirm_ids});if(a==='review')return call(a,{reviewer:$('#reviewer').value});if(a==='changes'){p.drafts[p.format].review='Changes requested';return call('save')}if(a==='addFact'){p.facts.push({fact_id:'F'+Date.now(),category:'context',wording:'',original_wording:'Writer addition',passage:'Writer addition — explicit confirmation required',location:'Writer addition',status:'uncertain',restriction:'',value:'',unit:'',period:'',qualifier:'',comparison:'',confirmation:null});invalidate();return render()}if(a==='addRef'){if(!$('#rt').value||!$('#rx').value){alert('Add a title and reference text.');return}p.references.push({id:'R'+Date.now(),title:$('#rt').value,format:$('#rf').value,industry:$('#rindustry').value,use_case:$('#ruse_case').value,outcome:$('#routcome').value,version:$('#rversion').value,entities:$('#re').value.split(',').map(x=>x.trim()).filter(Boolean),text:$('#rx').value,approved:false,active:true});return call('references')}if(a==='copy'){try{await navigator.clipboard.writeText(draftText());$('#message').innerHTML='<p class="save-info">Draft copied with its review status.</p>'}catch(e){$('#message').innerHTML='<div class="error">Clipboard unavailable. Download the draft instead.</div>'}return}if(a==='download'){let link=document.createElement('a');link.href=URL.createObjectURL(new Blob([draftText()],{type:'text/plain'}));link.download=p.format+'-draft.txt';link.click();URL.revokeObjectURL(link.href);return}await call(a)}
function showSource(id){let f=p.facts.find(f=>f.fact_id===id);$('#source-content').innerHTML=f?`<h2>Source evidence</h2><span class="pill">${esc(f.status)}</span><p>${esc(f.wording)}</p><p class="muted">${esc(f.location)}</p><pre>${esc(f.passage)}</pre>${f.confirmation?'<p class="muted">'+(f.confirmation.method==='accepted_available_intake'?'Accepted via Continue by ':'Confirmed by ')+esc(f.confirmation.by)+' · '+esc(f.confirmation.at)+'</p>':''}`:'Source unavailable';$('#source').showModal()}
function draftText(){let d=p.drafts[p.format];return `${p.demo?'FICTIONAL SAMPLE — ':''}DRAFT · ${d.review}\nAutomated checks: ${d.validation?.status||'Needs revalidation'}\n\n`+d.sections.map(s=>s.name+'\n'+s.text).join('\n\n')}
$('#close-source').onclick=()=>$('#source').close();fetch('/api/state').then(r=>r.json()).then(x=>{try{p=JSON.parse(sessionStorage.getItem(sessionKey)||'null')}catch(e){p=null}model=x.model;view=p?.plan?'plan':'facts';step=p?(p.plan_approved?2:1):0;render()}).catch(()=>$('#message').innerHTML='<div class="error">Cannot reach the local server. Restart Story Studio.</div>');
